### ISSUE TITLE
Exceptions do not hide items

### ISSUE THREAD

**Issue by DanDon** [galloween/custom-sidebar-v2#4]
Adding user specific exceptions and having them hidden does not hide them for that user??

```
........
],
    "exceptions": [
    {
        "user": [
            "Su"
        ],
        "base_order": false,
        "order": [
            {
                "item": "overview",
                "order": 1
            },
            {
                "item": "energy",
                "hide": true
            },
            {
                "item": "map",
                "hide": true
            },
            {
                "item": "logbook",
                "hide": true
            },
            {
                "item": "history",
                "hide": true
            },
            {
                "item": "media browser",
                "hide": true
            }
        ]
    }
    ]
}
```

**Comment by galloween** [comment]
@DanDon 
Hi! there was a bug - the script expected users in the exceptions to be lowercase. 
fixed it now! Update/re-download plugin, then hard-refresh the page and it should work.

<table><tr><td>
<img src="https://user-images.githubusercontent.com/2077754/146614332-6bf67f9b-f910-46a6-b8a2-9dff71f2eb57.png">
</td><td>
<img src="https://user-images.githubusercontent.com/2077754/146614355-a323819d-a336-4aac-a057-d8c83161e236.png">
</td></tr></table>

If it still doesnt work - check some advises [here](https://github.com/Villhellm/custom-sidebar/issues/40#issuecomment-968252152) and [here](https://github.com/galloween/custom-sidebar-v2#notes) and also take a look at the console for some possible errors. 
Current version of the script is 301217_2359 - check you have it in the console log!
There will also be an object with some data that may help you figure out the problem.
<img width="449" alt="CleanShot 2021-12-18 at 00 22 33@2x" src="https://user-images.githubusercontent.com/2077754/146614782-22b330cf-2cdd-4969-a3f4-bfe8b7e024bc.png">

**Comment by DanDon** [comment]
Installing the new version and hard reloading the page (or even using the page in an incognito window) still shows elements that are supposed to be hidden:

![Untitled](https://user-images.githubusercontent.com/595525/146615931-932fd1c3-6057-40ef-abab-2c3561bd8df5.png)

**Comment by galloween** [comment]
it looks like its not getting your `sidebar-order.json` file

normally you would see "orderConfig" in that object in the log:

<img src="https://user-images.githubusercontent.com/2077754/146616650-99d9d914-b214-4454-ac19-582b8ce92cb6.png" width="400">

you should also be able to see it in the Network tab:

<img src="https://user-images.githubusercontent.com/2077754/146616739-27092f9f-61f7-4374-9a43-910ec59e054f.png" width="500">

**Comment by DanDon** [comment]
I can see now that you're right that is does show up normally:

![Untitled](https://user-images.githubusercontent.com/595525/146617933-492de5ce-397e-4df0-8de9-8a6787975c50.png)

But it does not appear/load into the page when logged in as the user with exceptions??

**Comment by galloween** [comment]
it should! at least it does for me (I also have 2 users, both "admins" - whatever that means - but different sidebars, using exceptions). 

you could try to see if the file is where its supposed to be, while you are logged in as the other user.
but if its not there, Im afraid I dont have any idea why.

**Comment by DanDon** [comment]
Ah!! ... you have nailed the problem.

My users are not admins ... otherwise hiding the items would be pointless as they would be able to re-add them.

So the old one works with the user not having to be admin but this v2 doesn't load correctly if the user is not an admin??

**Comment by galloween** [comment]
not sure thats the reason... Also dont think the file is actually missing, any more.
new theory is the plugin cant find the sidebar DOM element. 
it may be because of different theme or something like that.

i added some more logging, if you re-download the plugin you should see more stuff in that log object, all of it needs to be truthy, including these 2 elements:

<img src="https://user-images.githubusercontent.com/2077754/146620261-9683111f-00a1-470f-bf59-1b1df449a381.png" width="450">

If you dont have them, take a screenshot of the Inspect/Elements, top of the page:

<img src="https://user-images.githubusercontent.com/2077754/146620384-66bb273d-daf9-4dbc-b40e-e82843a698f9.png" width="450">

hope we can figure it out, but now I have to go!

**Comment by 63OR63** [comment]
I made my exceptions to hide some items for all users except myself. At first It was working properly, but after some time, I assume after latest update, this addon started to hide items from me as it does for all other users. Let's say my username is `John Doe`, and my login is `john`, so I tried all variants, i.e.:
```json
"not_user": ["john doe", "John Doe", "john"]
```
Custom sidebar shows my `currentUser` in console as `john doe`.
I tried to clear site date, server restart, addon reinstall, another browser — the bug persists in all cases.
<details><summary>My full sidebar-order.json (click to expand)</summary>

```json
{
  "order": [
    {
      "item": "lovelace"
    },
    {
      "item": "map"
    },
    {
      "item": "history",
      "hide": true
    },
    {
      "item": "alarmo"
    },
    {
      "item": "a0d7b954_motioneye"
    },
    {
      "item": "7ad98f9c_zigbee2mqtt"
    },
    {
      "item": "a0d7b954_esphome"
    },
    {
      "item": "a0d7b954_grafana",
      "icon": "fapro:grafana"
    },
    {
      "item": "a0d7b954_influxdb",
      "icon": "fapro:influxdb"
    },
    {
      "item": "a0d7b954_nodered",
      "icon": "fapro:nodered"
    },
    {
      "item": "a0d7b954_vscode"
    },
    {
      "item": "shopping-list",
      "hide": true
    },
    {
      "item": "media-browser",
      "hide": true
    },
    {
      "item": "hacs",
      "name": "HACS",
      "icon": "fapro:hacs",
      "bottom": true
    },
    {
      "new_item": true,
      "item": "Supervisor",
      "href": "/hassio/dashboard",
      "icon": "mdi:home-assistant",
      "bottom": true
    },
    {
      "item": "developer-tools",
      "icon": "mdi:tools",
      "bottom": true
    },
    {
      "new_item": true,
      "item": "Сервер",
      "href": "/config/server_control",
      "icon": "mdi:cog-refresh",
      "bottom": true
    },
    {
      "item": "config",
      "bottom": true
    }
  ],
  "exceptions": [
    {
      "not_user": ["john doe", "John Doe", "john"],
      "order": [
        {
          "item": "hacs",
          "hide": true
        },
        {
          "item": "Supervisor",
          "hide": true
        },
        {
          "item": "developer-tools",
          "hide": true
        },
        {
          "item": "Сервер",
          "hide": true
        },
        {
          "item": "config",
          "hide": true
        },
        {
          "item": "history",
          "hide": true
        },
        {
          "item": "alarmo",
          "hide": true
        },
        {
          "item": "a0d7b954_motioneye",
          "hide": true
        },
        {
          "item": "7ad98f9c_zigbee2mqtt",
          "hide": true
        },
        {
          "item": "a0d7b954_esphome",
          "hide": true
        },
        {
          "item": "a0d7b954_grafana",
          "hide": true
        },
        {
          "item": "a0d7b954_influxdb",
          "hide": true
        },
        {
          "item": "a0d7b954_nodered",
          "hide": true
        },
        {
          "item": "a0d7b954_vscode",
          "hide": true
        }
      ]
    }
  ]
}
```
</details>

If I can submit some other logs/configs to help mitigate the problem I will gladly do so, as this functionality is crucial for me, I can't believe it wasn't implemented in Home Assistant after so many years of requesting and implementing as addons.

**Comment by wastingaeons** [comment]
> not sure thats the reason... Also dont think the file is actually missing, any more. new theory is the plugin cant find the sidebar DOM element. it may be because of different theme or something like that.

Hi, chiming in here, I am also seeing the same issue as reported. Comparing your console output to mine, the `DrawerLayoutElement` and `SideBarElement` both have valid DOM elements, however, under the 'non-admin' account when exceptions are enabled, `SidebarItemElement` is undefined. Under an admin account, `SideBarItemElement` is 'a'

![image](https://user-images.githubusercontent.com/2839483/147299237-66cbe172-c9e2-46cb-8821-5164eda0eb6d.png)

EDIT: Looks like this is why it breaks for non-admin users since they don't have the 'Configuration' menu: `element.tagName == 'A' && element.getAttribute('data-panel') == 'config'`

I removed the  `&& element.getAttribute('data-panel') == 'config'` and it seems to be working correctly, but unsure if it'll have other ramifications.

**Comment by illusive-c** [comment]
Kind of an old topic but this bug still seems to be present. We can only limit the sidebar for "admin" user. For the non-admins, the script throws this exception:
![image](https://user-images.githubusercontent.com/11490199/206046946-4dcefd1c-bff7-4df4-8fe5-53fad72cbbfc.png)
Works fine for admin users.
